LoginVenu
tupchiienko/InternetShop pull request #3
Opened 2021-04-21 15:04 UTC by Oleksandr0404

2021-04-21 15:34 UTC, sloboda89 commented on src/main/java/view/impl/LoginMenu.java
> +            User user = userService.login(login, password).getValue();
Please, avoid calling a method twice if you can avoid it. The method can contain heavy logic (e.g. call to the database).
You can save the result of `userService.login(login, password)` to a local variable and use it for both login checking and extracting user entity.

2021-04-21 15:34 UTC, sloboda89 commented on src/main/java/view/impl/LoginMenu.java
> +//    private void registerAdminSubMenu(Scanner scanner) {
Try to not merge commented code to master. If you going to use some code later keep it in your local branch or at least mark this code with TODO comment.

2021-04-29 14:14 UTC, tupchiienko requested changes

2021-04-29 14:14 UTC, tupchiienko commented on src/main/java/view/impl/LoginMenu.java
> +        showItems(items);
Rewrite method `showItems(String[] items)` in the Menu interface. it should print the data as follows:
\-----------------

0. Exit
1. Login
2. Register

\-----------------

```
        default void showItems(String[] items) {
            System.out.println("-------------");
            for (String item : items) {
                System.out.println(item);
            }
            System.out.println("-------------");
        }
```

2021-04-29 14:39 UTC, tupchiienko approved these changes

2021-04-29 14:41 UTC, mashina-or-not approved these changes

2021-04-29 14:41 UTC, merged