Userdao
tupchiienko/InternetShop pull request #7
Opened 2021-04-25 16:07 UTC by VolodymyrTistechok

class UserDaoImpl

2021-04-27 16:08 UTC, Oleksandr0404 approved these changes

2021-04-27 17:06 UTC, Oleksandr0404 approved these changes

2021-04-27 17:07 UTC, Oleksandr0404 approved these changes

2021-04-27 22:36 UTC, Oleksandr0404 approved these changes

2021-04-29 14:15 UTC, tupchiienko requested changes

2021-04-29 14:15 UTC, tupchiienko commented on src/main/java/dao/impl/UserDaoImpl.java
> +        return userMap;
It must return copy of `userMap`

2021-04-29 14:15 UTC, tupchiienko commented on src/main/java/dao/impl/UserDaoImpl.java
> +    private Map<String, User> userMap = new HashMap<>();
Initialize `userMap` in constructor `UserDaoImpl()` as `new TreeMap()`

2021-04-29 14:15 UTC, tupchiienko commented on src/main/java/dao/impl/UserDaoImpl.java
> +          return Optional.ofNullable(  userMap.replace(username, newUser));
Remove reduntant spaces

2021-04-29 14:15 UTC, tupchiienko commented on src/main/java/dao/impl/UserDaoImpl.java
>      public Optional<User> update(String username, User newUser) {
Make it like that:
```
    public Optional<Product> update(String name, Product newProduct) {
        Optional<Product> deletedProduct = delete(name);
        if (deletedProduct.isPresent()) {
            add(newProduct);
        }
        return deletedProduct;
    }
```

2021-04-29 14:43 UTC, Oleksandr0404 approved these changes

2021-04-29 15:24 UTC, tupchiienko approved these changes

2021-04-29 15:38 UTC, merged